refactoring: collection and stream tasks
notbadcodecom/hh-school-2022-java-collections-stream pull request #1
Opened 2022-12-06 23:42 UTC by notbadcodecom

- Задачи 1-7 переписал на стримах. В задачах 1 и 6 создавал стримами дополнительно переменную HashMap, в остальных задачах обошелся одним стримом.
- Задача 8 следующие исправления:
  - метод getNames: проверка списка через метод isEmpty(), использование тернарного оператора, stream.skip вместо удаления первого элемента списка;
  - метод getDifferentNames: создание сэта без стримов;
  - метод convertPersonToString: StringBuilder вместо конкатенации строк, Optional вместо проверки на null, замена повторного использования имени на отчество;
  - метод getPersonNames: переписал на стримы;
  - метод hasSamePersons: переписал на метод коллекций retainAll;
  - метод countEven: использовал метод count в стримах.

2022-12-07 08:24 UTC, genroelgvozo requested changes

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task3.java
> +      if (!person1.getSecondName().equals(person2.getSecondName())) {
сложновато читается, не правда ли?)

посмотри на методы у компаратора, которые возвращает Comparator.comparing(getter)

и еще - твой код в целом может и упасть.. А когда?

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +                    .map(areaId -> person.getFirstName() + " - " + areasNames.get(areaId)))
это ок, но в целом более концептуально вынести в метод getPersonDescription, чтобы инкапсулировать логику склеивания и тут не вдавать в подробности. И в метод приимать не areName а area целиком, потому что вдруг она поменяется, и у арейки нужно будет еще какое-нибудь поле, пускай это метод решает сам

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task7.java
> +            .flatMap(company -> company.getVacancies().stream())
тут все ок, но чисто на вкус мне нравится больше
.map(Company::getVacancies)
.flatMap(Collection::stream)
когда меньше стрелочек а больше ссылок отдельные методы, но это вкусовщина, просто чтобы знал

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return (persons.isEmpty()) ? Collections.emptyList() : persons.stream()
надо ли проверять на пустоту? skip(1) на пустом листе обламается?

ну и вопрос - а чего не так то было?

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return stringBuilder.toString();
вообщем то чуточку стало лучше, но по факту - опшинал вместо однострочного ифа..
А баг то так и остался.. (подумай какой)

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +            .collect(Collectors.toMap(Person::getId, this::convertPersonToString));
твой код будет иногда падать, в отличие от моего...

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return !persons1.isEmpty();
ох, передам я тебе Set.of(person1) в первом параметре

2022-12-07 08:24 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return numbers.filter(number -> number % 2 == 0).count();
а чем лучше?

2022-12-07 09:01 UTC, notbadcodecom commented on src/main/java/tasks/Task8.java
> +    return numbers.filter(number -> number % 2 == 0).count();
Когда писал, руководствовался принципом: есть специальный метод.
Сейчас посмотрел, лямбда не компилирует в таком случае (local variables must be effectively final).
Лямбда использует значения, а не переменные, во избежание ошибок.
И, если то важно, count бы тоже выдал ошибку без указания типа.

2022-12-07 09:03 UTC, notbadcodecom commented on src/main/java/tasks/Task7.java
> +            .flatMap(company -> company.getVacancies().stream())
Согласен, выглядит аккуратнее.

2022-12-07 09:04 UTC, notbadcodecom commented on src/main/java/tasks/Task6.java
> +                    .map(areaId -> person.getFirstName() + " - " + areasNames.get(areaId)))
Согласен, поправлю.

2022-12-07 09:33 UTC, notbadcodecom commented on src/main/java/tasks/Task3.java
> +      if (!person1.getSecondName().equals(person2.getSecondName())) {
Да, так действительно лучше.
Код упадет, если будет null в имени или фамилии.
Спасибо, поправил.

2022-12-07 10:02 UTC, notbadcodecom commented on src/main/java/tasks/Task8.java
> +    return (persons.isEmpty()) ? Collections.emptyList() : persons.stream()
- На пустоту, скорее всего не надо проверять, это будет просто пустой поток.
- persons.remove(0) удаляет первый элемент и сдвигает остальные n. То есть на пустом месте усложняется асимптотическая сложность. skip(1) просто пропустит первый элемент стрима.

2022-12-07 10:14 UTC, notbadcodecom commented on src/main/java/tasks/Task8.java
> +    return stringBuilder.toString();
Не понимаю какой баг, только если null в место Person передадут.

2022-12-07 11:31 UTC, notbadcodecom commented on src/main/java/tasks/Task8.java
> +            .collect(Collectors.toMap(Person::getId, this::convertPersonToString));
Понял, IllegalStateException из-за одинаковых id, если в коллекции persons будут не уникальные объекты.
Исправил.

2022-12-07 12:26 UTC, notbadcodecom commented on src/main/java/tasks/Task8.java
> +    return !persons1.isEmpty();
Понял, исправил.

2022-12-07 12:42 UTC, genroelgvozo requested changes

2022-12-07 12:42 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +    Map<Integer, Area> areasNames = areas.stream()
только это уже не areaNames

и название метода в целом ок, но лучше чтобы он отражал что делает (составляет описание) а не как или из чего состоит
а то если захотим еще дату рождения добавить, метод переименовывать надо)
это как в css сделать стиль .blue потому что кнопка синяя, а не потому что акцентная

2022-12-07 12:42 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +      Optional.ofNullable(person.getFirstName()).ifPresent(name -> stringBuilder.append(" ").append(name));
если secondName==null, то будет пробел в начале лишний

И в целом это тримом можно пофиксить, но суть в том как раз, что когда мы погружаемся до уровня "как сделать" и пишем все эти технические ифчики, стрингбилдеры и т.д. в таких прикладных простых методах, очень просто совершить ошибку. А вот если писать код в стиле "что сделать" не вдаваясь в детали, то будет проще.. хмм, кажется у стримов есть Collectors.joining() =)

2022-12-07 12:42 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +    return numbers.filter(number -> number % 2 == 0).count();
в моем коде как раз все ок, потому что она эффективли финал (я ее в поле вынес)
но тут сложный нюанс, как минимум плохо передавать в таком случае стрим, как максимум - стрим может быть параллельным, и тогда ++ не сработает нормально

2022-12-07 13:07 UTC, notbadcodecom commented on src/main/java/tasks/Task6.java
> +    Map<Integer, Area> areasNames = areas.stream()
Понял, исправил.

2022-12-07 13:08 UTC, notbadcodecom commented on src/main/java/tasks/Task8.java
> +      Optional.ofNullable(person.getFirstName()).ifPresent(name -> stringBuilder.append(" ").append(name));
Поправил.

2022-12-07 13:12 UTC, notbadcodecom commented on src/main/java/tasks/Task8.java
> +    return numbers.filter(number -> number % 2 == 0).count();
Ок.

2022-12-08 10:58 UTC, genroelgvozo approved these changes

2022-12-08 11:34 UTC, merged